### GET Livraisons
GET http://localhost:3010/Livraisons

### GET Unique Livraisons
GET http://localhost:3010/Livraisons/FD28465937BE

### GET Driver
GET http://localhost:3010/Driver/emma@fastdeliver.com

### GET Client
GET http://localhost:3010/Client

### GET Unique Client
GET http://localhost:3010/Client/client1@example.com

### PATCH CLIENT
PATCH http://localhost:3010/Client/client1@example.com
Content-Type: application/json

{
  "Nom": "Sam Gamegie",
  "Telephone": "0604567890",
  "Addresse": "12 rue de la paix, 59000 Lille"
}

### DELETE Livraisons
DELETE http://localhost:3010/Livraisons/FD28465937BE

### POST Livraisons
POST http://localhost:3010/Livraisons
Content-Type: application/json

{
  "NumSuivis": "FD58465938BE",
  "Date": "2021-03-01",
  "ClientEmail": "client1@example.com",
  "Addresse": "12 rue de la paix",
  "Poids": "5 kg",
  "Status": "En attente",
  "Livreur": "emma@fastdeliver.com",
  "Instructions": "Fragile"
}